service: stock-empty 
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  producer:
    handler: handler.producer
    events:
      - sqs: "arn:aws:sqs:ap-northeast-2:967699999360:step5.fifo"

plugins:
  - serverless-lift 

	



